import React from 'react';
import Paragraph from '../components/Paragraph';

const paragraphs = [
    { id: 1, chapter: 1, title: "Dywanowe początki", text: "Brak tradycji motoryzacyjnych w rodzinie nie był powodem moich zmartwień, przynajmniej w tamtym okresie. Z samochodów na ulicy potrafłem rozpoznać dosłownie kilka, z naszym rodzimym Maluchem na czele. Z daleka nie wiedziałem czy to jedzie Polonez czy może Fiat 125, o poprawnym wskazywaniu marki po dźwięku silnika nawet nie wspominając. Właściwie nie było mi to potrzebne do szczęścia, miałem to w... poważaniu i nie narzekałem na braki w swojej wiedzy. Jedną z ulubionych zabaw z dzieciństwa były „wyścigi” resoraków (...). Z perspektywy czasu okazało się, że był to mój pierwszy Test Drive Unlimited, w jakiego miałem okazję grać. Nie potrzebowałem komputera ani nawet klawiatury, których posiadanie wówczas i tak było raczej niemożliwe. Zabawa totalnie unplugged, ale zabawa przednia, ograniczona jedynie moją wyobraźnią, która z dnia na dzień powiększała się chyba o całą galaktykę. Niestety, mój dywan zaprogramowany był tylko na tryb single player. Dało się co prawda zagrać z siostrą w trybie współdzielonego dywanu, ale po pierwsze jej jakoś bliżej było do lalek, a po drugie bardzo nie lubiłem włosów z tej strony dywanu." },
    { id: 2, chapter: 2, title: "Zanim zjawił się Siemkins", text: "(..) Początkowo TDU było dość elitarne – grę posiadali zapaleńcy dysponujący mocnym sprzętem, stałym dostępem do Internetu (gros osób wciąż miało jedynie prosty modem, gdzie rachunki rosły proporcjonalnie do czasu spędzanego w sieci), niebojący się wydać 100 zł na nieznaną wcześniej samochodówkę (nie mam tu na myśli całej serii Test Drive, która istniała od 1987 roku), a ponadto posiadający kontrolera w postaci pada lub kierownicy (..) O’ahu karmiło zmysły, wyścigi zapewniały adrenalinę i stały przypływ gotówki. Test Drive Unlimited zaliczył udany debiut i wkupił się w łaski graczy, którzy pokochali ten tytuł. A miłość to była długa i trudna…" },
    { id: 3, chapter: 3, title: "Przebiegi i prosta fzyka", text: "W tym miejscu wszystkim niewtajemniczonym należy się wyjaśnienie tej sytuacji. Jak doskonale wiemy, w tzw. real-life wartość samochodu po pierwsze spada z czasem, jaki mija od daty zakupu, a po drugie, co ma prosty związek z pierwszym faktem, zależy od ilości przejechanych kilometrów. Im starsze auto, tym tańsze (z zasady, bowiem egzemplarzy kolekcjonerskich i innych wychuchanych do ostatniej śrubki cudeniek nie mam na myśli), im więcej wskazuje licznik pokonanych kilometrów, tym większe jego fzyczne zużycie, mniejsza sprawność, a co za tym idzie niższa cena. Otóż w TDU było niemal identycznie... z tą niewielką różnicą, że dokładnie na odwrót (...) Ilość kilometrów, jakie wskazywał licznik, była wyznacznikiem atrakcyjności – im wyższy przebieg, tym auto było więcej warte. Ta zależność jest bardzo prosta do wytłumaczenia i posiada solidne podstawy logiczne. Otóż kilometry zdobywało się jeżdżąc, a jazda wymagała grania. Trudno powiększać licznik przebytych kilometrów nie grając – to oczywiste. (...)" },
    { id: 4, chapter: 4, title: "Jedno życie", text: "(...) Dla mnie profl online był synonimem wirtualnego życia, a to podobnie jak w realu uważałem, było tylko jedno. Z wielkim smutkiem przyjąłem informację o odmowie współpracy i wypowiedzeniu, jakie złożył mój dysk twardy. Jak później się okazało trafłem na felerną serię Segate Baracudy, gdzie ponad 30% wszystkich dysków było do wyrzucenia, a większość z nich odmawiała współpracy w ciągu pierwszego miesiąca. Pech, że moja Baracuda pożyła ponad rok i szlag ją trafł w najmniej spodziewanym momencie. Pięć lat gromadzenia danych poszło się bezpowrotnie paść na łączkę. Materiały ze studiów, praca magisterska w wersji niemal fnalnej, zdjęcia, dokumenty, programy, wszystko. A skoro wszystko to i save z Test Drive Unlimited. (..) Jeszcze gorzej było z moim wirtualnym życiem. Co prawda posiadałem niejedną kopię zapasową swoich postępów z gry, bo doskonale wiedziałem, że kapryśnością TDU nie ustępuje żadnej kobiecie w trudnym dla niej czasie, ale co z tego, skoro przechowywałem je na innej partycji, jednak w ramach tego samego, śmiertelnie uszkodzonego dysku twardego? (..) " },
    { id: 5, chapter: 5, title: "New (not) home", text: " (...) Wciąż byłem na przemian zadowolony i dumny z odwagi stawianych po nieznanym gruncie kroków, a z drugiej strony kompletnie zagubiony i przerażony, pytający się o kolejny ruch, przyjmując, że chyba nie ma na świecie drugiej takiej osoby, która wiedziałaby równie mało co ja na jakiś temat, a mimo to podjęła się próby realizacji zadania, nie dysponując żadnymi środkami na wynajęcie specjalistów znających się na rzeczy. Pierwszym krokiem, który musiałem wykonać, było dowiedzenie się, czego nie wiem oraz co lub kto będzie mi potrzebny, aby zrobić coś, czego póki co nawet nie potrafłem dobrze nazwać. (...) " },
]

const BookPage = () => {

    const paragraphList = paragraphs.map(paragraph => (
        <Paragraph key={paragraph.id} {...paragraph} />
    ))

    return (
        <div className="book" >
            {paragraphList}
        </div>
    );
}

export default BookPage;